# Generated by Django 4.1 on 2022-09-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('foodConsumed', models.FloatField()),
                ('foodWasted', models.FloatField()),
                ('clients', models.IntegerField()),
                ('absences', models.IntegerField()),
            ],
        ),
    ]
