# Generated by Django 4.1 on 2022-09-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_daydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.CharField(max_length=50)),
                ('suplier', models.CharField(max_length=100)),
                ('stock', models.FloatField()),
                ('item', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
            ],
        ),
    ]
