# Generated by Django 4.1 on 2022-09-06 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='stock',
            new_name='ammount',
        ),
    ]
