# Generated by Django 4.1 on 2022-09-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_rename_stock_orders_ammount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='statusBg',
            field=models.CharField(default='#FEC90F', max_length=20),
        ),
    ]
